(require 'magit)
(global-set-key (kbd "C-x g") 'magit-status)
(add-hook 'magit-log-edit-mode-hook 'vimp-insert-state)
(define-key magit-status-mode-map "e" 'next-line)
(define-key magit-status-mode-map "u" 'previous-line)
(define-key magit-status-mode-map "n" 'magit-unstage-item)
(define-key magit-status-mode-map "i" 'magit-stage-item)
