(add-hook 'direx:direx-mode-hook 'turn-off-vimp-mode)
(define-key direx:direx-mode-map (kbd "j") 'direx:next-item)
(define-key direx:direx-mode-map (kbd "k") 'direx:previous-item)
(define-key direx:direx-mode-map (kbd "h") 'direx:up-item)
(define-key direx:direx-mode-map (kbd "l") 'direx:down-item)
(define-key direx:direx-mode-map (kbd "o") 'direx:maybe-find-item)
