; VIMP LEADER
(global-vimp-leader-mode)
(vimp-leader/set-leader ",")
(vimp-leader/set-key "=" 'balance-windows)
(vimp-leader/set-key "a" 'helm-git-grep-at-point)
(vimp-leader/set-key "d" 'sql-connect)
(vimp-leader/set-key "e" 'next-error)
(vimp-leader/set-key "g" 'magit-status)
(vimp-leader/set-key "h" 'vc-version-ediff)
(vimp-leader/set-key "l" 'split-window-below)
(vimp-leader/set-key "'" (kbd "yse'"))
(vimp-leader/set-key "\"" (kbd "yse\""))
(vimp-leader/set-key "r" (lambda() (interactive) (kbd "ysiW")))
(vimp-leader/set-key "t" 'google-this)
(vimp-leader/set-key ";" 'helm-mini)
(vimp-leader/set-key "w" 'previous-error)
(vimp-leader/set-key "z" (lambda () (interactive) (save-buffers-kill-terminal 1)))
(vimp-leader/set-key-for-mode 'sgml-mode "<right>" 'tagedit-forward-slurp-tag)
(vimp-leader/set-key-for-mode 'sgml-mode "<left>" 'tagedit-forward-barf-tag)
