(custom-set-variables
 '(lyqi:prefered-languages '(english))
 '(lyqi:prefered-octave-mode 'absolute)
 '(lyqi:keyboard-mapping 'qwerty)
 '(lyqi:custom-key-map '(("w" "\\trill")
                         ("x" (space-around . "\\appoggiatura"))
                         ("n" "~")
                         ("," "(")
                         (";" ")")
                         (":" "[")
                         ("=" "]")
                         ("\C-m" lyqi:insert-pipe-and-return)
                         ("$" lyqi:insert-pipe-and-return)))
 '(lyqi:midi-backend 'osx)
 '(lyqi:pdf-command "open")
 '(lyqi:midi-command "open")
)
