;; VIMP LEADER
(vimp-leader/set-leader ",")
(vimp-leader/set-key "f" 'recentf-ido-find-file)
(vimp-leader/set-key "b" 'ido-switch-buffer)
(vimp-leader/set-key "n" 'winring-new-configuration)
(vimp-leader/set-key "r" 'winring-rename-configuration)
(vimp-leader/set-key "d" 'sql-connect)
(vimp-leader/set-key "l" 'split-window-below)
(vimp-leader/set-key "=" 'balance-windows)
(vimp-leader/set-key "g" 'magit-status)
(vimp-leader/set-key "h" 'vc-version-ediff)
(vimp-leader/set-key "t" 'helm-ls-git-ls)
(vimp-leader/set-key "e" 'next-error)
(vimp-leader/set-key "w" 'previous-error)
(vimp-leader/set-key "c" (lambda () (interactive) (org-clock-in '(4))))
(vimp-leader/set-key "o" 'org-switchb)
